include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    depend_on_referenced_packages: false
    directives_ordering: false