name: food_quest
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Supabase
  supabase_flutter: ^1.10.19

  # Env
  flutter_dotenv: ^5.1.0

  # State Management
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.1
  riverpod_annotation: ^2.1.6
  freezed: ^2.4.3
  flutter_datetime_picker_plus: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1

  # Tools
  import_sorter: ^4.6.0
  intl: ^0.18.1
  flutter_gen: ^5.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  uuid: ^4.2.1

  # Routing
  auto_route: ^7.8.4

  # UI
  cupertino_icons: ^1.0.2
  extended_image: ^8.1.1
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  salomon_bottom_bar: ^3.3.2
  top_snackbar_flutter: ^3.1.0

  #Loading
  loading_animation_widget: ^1.2.0+4

  # リンク
  url_launcher: ^6.1.14

  # 画像選択
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

  # Generate
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  auto_route_generator: ^7.3.2

  # LocalData
  shared_preferences: ^2.2.2

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: AppColor
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
