name: Android Build

on:
  pull_request:
    # プルリク作成時とプルリクにコミットが行われた時、再開された時
    types: [opened, synchronize, reopened]

env:
  DATABASE_URL: ${{secrets.VAR_URL}}
  SHADOW_DATABASE_URL: ${{secrets.VAR_ANONKEY}}

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cat > .env <<EOF
          VAR_URL=${{ secrets.VAR_URL }}
          VAR_ANONKEY=${{ secrets.VAR_ANONKEY }}
          EOF
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.6"
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build appbundle
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          name: android
          path: ./build/app/outputs/
          retention-days: 1