name: iOS Build

on:
  pull_request:
    # プルリク作成時とプルリクにコミットが行われた時、再開された時
    types: [opened, synchronize, reopened]

env:
  DATABASE_URL: ${{secrets.VAR_URL}}
  SHADOW_DATABASE_URL: ${{secrets.VAR_ANONKEY}}

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cat > .env <<EOF
          VAR_URL=${{ secrets.VAR_URL }}
          VAR_ANONKEY=${{ secrets.VAR_ANONKEY }}
          EOF
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.6"
          channel: "stable"
          cache: true
      - run: flutter pub get
      # iOS Build
      - run: flutter build ios --release --no-codesign
      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          # 保存ファイル名（name.zip）
          name: ios
          # 保存するファイル
          path: ./build/ios/
          # 保存期間（日）
          retention-days: 1